### ISSUE TITLE
Even the swift demo project is not working

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1037]
## What did you do?
Try to run the sample project from the sdk version 3.1.8, getting the error on ChatPresenter.swift

IssueNo:1) Cannot find type '_ChatChannelListRouter' in scope
The method does not override any method from its superclass

class DemoChatChannelListRouter: _ChatChannelListRouter<NoExtraData> {
    override func openCreateNewChannel() {
        let storyboard = UIStoryboard(name: "Main", bundle: .main)
        
        let chatViewController = storyboard.instantiateViewController(withIdentifier: "CreateChatViewController")
            as! CreateChatViewController
        chatViewController.searchController = rootViewController.controller.client.userSearchController()
        
        navigationController?.pushViewController(chatViewController, animated: true)
    }
}

![Screenshot 2021-04-30 at 12 56 41 AM](https://user-images.githubusercontent.com/78809766/116662766-30791f00-a964-11eb-802d-92d52557e9f1.png)

******************************************************************************************************************
Issue No:2) Getting error on  DemoAppCoordinator.swift class
'channelListRouter' is inaccessible due to 'internal' protection level
        UIConfig.default.navigation.channelListRouter = DemoChatChannelListRouter.self
It seems to work after comment the above line
![Screenshot 2021-04-30 at 12 54 24 AM](https://user-images.githubusercontent.com/78809766/116662855-4f77b100-a964-11eb-8883-4077de9cbc36.png)
******************************************************************************************************************
Issue No:3) Crashes When clicks on a channel having texts, images, and videos in the channel list. It logs as below

*** Assertion failure in -[StreamChatUI.ChatMessageListCollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], UICollectionView.m:6379
2021-04-30 02:17:58.803878-0400 ChatSample[9900:83170] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier outgoing_0__СhatMessageCollectionViewCell<NoExtraData>_ChatMessageContentView<NoExtraData> - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2042191f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff2077156a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff23d8c8d6 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 2322
	5   UIKit                               0x000000010c141617 -[UICollectionViewAccessibility _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 659
	6   UIKitCore                           0x00007fff23d8ca4f -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 88
	7   StreamChatUI                        0x0000000109841f77 $s12StreamChatUI01_B13MessageListVCC14collectionView_13cellForItemAtSo012UICollectionH4CellCSo0mH0C_10Foundation9IndexPathVtF + 663
	8   StreamChatUI                        0x0000000109843155 $s12StreamChatUI01_B13MessageListVCC14collectionView_13cellForItemAtSo012UICollectionH4CellCSo0mH0C_10Foundation9IndexPathVtFTo + 165
	9   UIKitCore                           0x00007fff23d773ba -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 410
	10  UIKitCore                           0x00007fff23d7721a -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 31
	11  UIKitCore                           0x00007fff23d7c840 -[UICollectionView _updateVisibleCellsNow:] + 6148
	12  UIKitCore                           0x00007fff23d81abc -[UICollectionView layoutSubviews] + 351
	13  UIKitCore                           0x00007fff24bf8504 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	14  QuartzCore                          0x00007fff27b1bc2b -[CALayer layoutSublayers] + 258
	15  QuartzCore                          0x00007fff27b2219d _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	16  QuartzCore                          0x00007fff27b2df3f _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	17  QuartzCore                          0x00007fff27a6d44c _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	18  QuartzCore                          0x00007fff27aa4233 _ZN2CA11Transaction6commitEv + 783
	19  QuartzCore                          0x00007fff27aa53ef _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	20  CoreFoundation                      0x00007fff2038f1f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	21  CoreFoundation                      0x00007fff20389a77 __CFRunLoopDoObservers + 547
	22  CoreFoundation                      0x00007fff2038a01a __CFRunLoopRun + 1113
	23  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	24  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	25  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	26  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	27  libswiftUIKit.dylib                 0x00007fff551885f2 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 98
	28  ChatSample                          0x00000001089f530a $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 122
	29  ChatSample                          0x00000001089f527e $s10ChatSample11AppDelegateC5$mainyyFZ + 46
	30  ChatSample                          0x00000001089f5359 main + 41
	31  libdyld.dylib                       0x00007fff2025a3e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier outgoing_0__СhatMessageCollectionViewCell<NoExtraData>_ChatMessageContentView<NoExtraData> - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 (9ABED8A8-B158-45A5-9E5C-69B958EE7A2E) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12
******************************************************************************************************************

Issue No4:) When I am trying to upload multiple images, the very first image selection is not showing on the input box section, but  its showing after the second image selection onwards
![Simulator Screen Shot - iPhone 12 - 2021-04-30 at 02 34 29](https://user-images.githubusercontent.com/78809766/116658115-7da5c280-a95d-11eb-848b-5595b4ca40fa.png)
![Uploading Simulator Screen Shot - iPhone 12 - 2021-04-30 at 02.34.58.png…]()
 **************************************************************************************************************************
Issue No:5) When the image upload option on iPhone 12 simulator , select on photo crashes the SDK, getting error as below
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'No available types for source 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   UIKitCore                           0x00007fff23e7561f -[UIImagePickerController mediaTypes] + 0
	3   StreamChatUI                        0x000000010c82d1d1 $s12StreamChatUI01_B17MessageComposerVCC11imagePickerSo07UIImageH10ControllerCvgAFyXEfU_ + 209
	4   StreamChatUI                        0x000000010c82d055 $s12StreamChatUI01_B17MessageComposerVCC11imagePickerSo07UIImageH10ControllerCvg + 277
	5   StreamChatUI                        0x000000010c8344b9 $s12StreamChatUI01_B17MessageComposerVCC21showAttachmentsPickeryyF11actionSheetL_So17UIAlertControllerCvgySo0L6ActionCcfU0_ + 217
	6   StreamChatUI                        0x000000010c717c09 $sSo13UIAlertActionCIegg_ABIeyBy_TR + 73
	7   UIKitCore                           0x00007fff23b06104 -[UIAlertController _invokeHandlersForAction:] + 105
	8   UIKitCore                           0x00007fff23b06a0a __103-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:dismissCompletion:]_block_invoke.452 + 16
	9   UIKitCore                           0x00007fff23e3a17f -[UIPresentationController transitionDidFinish:] + 947
	10  UIKitCore                           0x00007fff23e3ec28 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.502 + 199
	11  UIKitCore                           0x00007fff23f8e1d0 -[_UIViewControllerTransitionContext completeTransition:] + 90
	12  UIKitCore                           0x00007fff24bec248 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 779
	13  UIKitCore                           0x00007fff24bbcb0e -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 231
	14  UIKitCore                           0x00007fff24bbd0ad -[UIViewAnimationState animationDidStop:finished:] + 259
	15  UIKit                               0x000000010f03eca9 -[UIViewAnimationStateAccessibility animationDidStop:finished:] + 203
	16  UIKitCore                           0x00007fff24bbd231 -[UIViewAnimationState animationDidStop:finished:] + 647
	17  UIKit                               0x000000010f03eca9 -[UIViewAnimationStateAccessibility animationDidStop:finished:] + 203
	18  QuartzCore                          0x00007fff27b2f09c _ZN2CA5Layer23run_animation_callbacksEPv + 308
	19  libdispatch.dylib                   0x000000010ce649c8 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010ce72e75 _dispatch_main_queue_callback_4CF + 1152
	21  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	23  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	24  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	25  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	26  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	27  libswiftUIKit.dylib                 0x00007fff551885f2 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 98
	28  ChatSample                          0x000000010b85d30a $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 122
	29  ChatSample                          0x000000010b85d27e $s10ChatSample11AppDelegateC5$mainyyFZ + 46
	30  ChatSample                          0x000000010b85d359 main + 41
	31  libdyld.dylib                       0x00007fff2025a3e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'No available types for source 0'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 (9ABED8A8-B158-45A5-9E5C-69B958EE7A2E) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12

![Simulator Screen Shot - iPhone 12 - 2021-04-30 at 02 52 38](https://user-images.githubusercontent.com/78809766/116659350-78497780-a95f-11eb-8551-e6a20f626f73.png)

**************************************************************************************************************************

## What did you expect to happen?

At least the sample app will work as perfect.

## What happened instead?
Failed to run

## GetStream Environment
**GetStream Chat version:** 3.1.8
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**14.2
**Swift version:**5.0
**Xcode version:**12.4
**Device:**Both simulator and ipad

## Additional context

I would like to integrate the swift framework into my existing objective C project, but  even the sample app in the sdk itself is failed to run . 

![Screenshot 2021-04-30 at 12 54 24 AM](https://user-images.githubusercontent.com/78809766/116652166-a96f7b00-a952-11eb-9403-558b5040fe60.png)

![Screenshot 2021-04-30 at 12 56 41 AM](https://user-images.githubusercontent.com/78809766/116652179-b0968900-a952-11eb-927a-e07de1c94033.png)

![Screenshot 2021-04-30 at 12 55 59 AM](https://user-images.githubusercontent.com/78809766/116652193-b4c2a680-a952-11eb-8332-40313cd13b99.png)

**Comment by AmalJose-01** [comment]
Exactly the same issues for me too.. Engane ettal mathi

**Comment by VojtaStavik** [comment]
Hi @vineethnkforios, thank you for your report. I believe all this (except #4) is fixed in the latest release. Please let me know in case you see the issues again.

@AmalJose-01 We plan to release a stable version of the UI SDK within a couple of weeks. Please stay tuned, we're almost done 🚀

**Comment by vineethnkforios** [comment]
@VojtaStavik  Issue No 3 still exists on Version 3.1.9 (Crashes When clicks on a channel having texts, images, and videos in the channel list. It logs as below)

Log:
2021-05-05 01:11:58.168586-0400 ChatSample[7431:53609] *** Assertion failure in -[StreamChatUI.ChatMessageListCollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], UICollectionView.m:6379
2021-05-05 01:11:58.191622-0400 ChatSample[7431:53609] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier outgoing_0__СhatMessageCollectionViewCell<NoExtraData>_ChatMessageContentView<NoExtraData> - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2042191f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff2077156a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff23d8c8d6 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 2322
	5   UIKit                               0x000000010ec2a617 -[UICollectionViewAccessibility _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 659
	6   UIKitCore                           0x00007fff23d8ca4f -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 88
	7   StreamChatUI                        0x000000010e209337 $s12StreamChatUI01_B13MessageListVCC14collectionView_13cellForItemAtSo012UICollectionH4CellCSo0mH0C_10Foundation9IndexPathVtF + 663
	8   StreamChatUI                        0x000000010e20a515 $s12StreamChatUI01_B13MessageListVCC14collectionView_13cellForItemAtSo012UICollectionH4CellCSo0mH0C_10Foundation9IndexPathVtFTo + 165
	9   UIKitCore                           0x00007fff23d773ba -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 410
	10  UIKitCore                           0x00007fff23d7721a -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 31
	11  UIKitCore                           0x00007fff23d7c840 -[UICollectionView _updateVisibleCellsNow:] + 6148
	12  UIKitCore                           0x00007fff23d81abc -[UICollectionView layoutSubviews] + 351
	13  UIKitCore                           0x00007fff24bf8504 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	14  QuartzCore                          0x00007fff27b1bc2b -[CALayer layoutSublayers] + 258
	15  QuartzCore                          0x00007fff27b2219d _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	16  QuartzCore                          0x00007fff27b2df3f _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	17  QuartzCore                          0x00007fff27a6d44c _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	18  QuartzCore                          0x00007fff27aa4233 _ZN2CA11Transaction6commitEv + 783
	19  UIKitCore                           0x00007fff246958cf _UIApplicationFlushRunLoopCATransactionIfTooLate + 106
	20  UIKitCore                           0x00007fff247462ce __processEventQueue + 14865
	21  UIKitCore                           0x00007fff2473c877 __eventFetcherSourceCallback + 104
	22  CoreFoundation                      0x00007fff2039038a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x00007fff20390282 __CFRunLoopDoSource0 + 180
	24  CoreFoundation                      0x00007fff2038f764 __CFRunLoopDoSources0 + 248
	25  CoreFoundation                      0x00007fff20389f2f __CFRunLoopRun + 878
	26  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	27  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	28  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	29  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	30  libswiftUIKit.dylib                 0x00007fff551885f2 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 98
	31  ChatSample                          0x000000010d3afb0a $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 122
	32  ChatSample                          0x000000010d3afa7e $s10ChatSample11AppDelegateC5$mainyyFZ + 46
	33  ChatSample                          0x000000010d3afb59 main + 41
	34  libdyld.dylib                       0x00007fff2025a3e9 start + 1
	35  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier outgoing_0__СhatMessageCollectionViewCell<NoExtraData>_ChatMessageContentView<NoExtraData> - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 (9ABED8A8-B158-45A5-9E5C-69B958EE7A2E) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12

**Comment by b-onc** [comment]
Hello @vineethnkforios ,

We've resolved this issue and merged the fix with #1007
