### ISSUE TITLE
ChatMessageSearchController.loadNextMessages fails for queries with a custom link type

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2224]
## What did you do?

```
var controller = chatClient.messageSearchController()

let query = MessageSearchQuery(
    channelFilter: .equal(.cid, to: channel.cid),
    messageFilter: .withAttachments([.linkPreview]),
    sort: [.init(key: .relevance, isAscending: false)],
    pageSize: 20
)

controller.search(query)
```

then later,

```
controller.loadNextPage()
```

## What did you expect to happen?

we get more results

## What happened instead?

the get stream server errors out
<img width="1512" alt="Screen Shot 2022-08-08 at 1 32 53 PM" src="https://user-images.githubusercontent.com/3814772/183512108-e3bbda91-19b8-4c94-b67d-eb99124a667a.png">

**Comment by hugobernalstream** [comment]
Hi @AndrewSB,

Thanks for your report. I'm reviewing the issue with the team and will get back to you soon with an answer.

Regards,
Hugo

**Comment by hugobernalstream** [comment]
Hi @AndrewSB,

Could you try and do the message search without the `sort: [.init(key: .relevance, isAscending: false)]` parameter? we currently don't support it when loading following pages. We now have an internal ticket for tracking this issue down and add this missing functionality as soon as possible.

We'll update this issue once the functionality is released in a future version.

Regards,
Hugo

**Comment by jfru** [comment]
Hey Team,
How's it going? Any updates on this issue. It's blocking the release of our media lists in chat which are becoming increasingly important as volume picks up.
We'd really appreciate a solution here 🙏

**Comment by nuno-vieira** [comment]
Hi @jfru!

We bumped the priority on this one, and we will start working on it next week. 

The ETA for releasing this is about 2 weeks. But we will keep you posted!

Best,
Nuno

**Comment by AndrewSB** [comment]
@martinmitrevski i think this might be related to that workaround we did to prevent being booted out of a chat thread

this is how we create a channel destination, i don't believe its synchronized in the solution we came up with together

<img width="690" alt="Screen Shot 2022-09-09 at 6 28 58 PM" src="https://user-images.githubusercontent.com/3814772/189463685-6bcf3326-a064-4126-936a-f9efb4e8860d.png">

**Comment by jfru** [comment]
Hi Team. What's the latest on this PR?

**Comment by polqf** [comment]
Hi @jfru, we had some items that got more priority over this one, so unfortunately the implementation has not yet started.
We will let you know when we start working on it.

**Comment by jfru** [comment]
Guys, I'm sorry for being blunt here, but this isn't good enough. This is a basic feature that is part of every other chat app. We opened this issue 2 month ago! We're a startup. We simply can't afford to wait this long for bog standard functionality. Please bump this up your priority list and get it out to us asap.

**Comment by shodgetts** [comment]
Hi @jfru, we understand this is a feature for your app, but the iOS team at Stream has other priorities currently higher on our list. We have to prioritize issues that are the highest impact on our overall customer base. Can you please drop me an email, stephen@getstream.io, and we can continue the discussion? Continuing to comment on these GH issues is not going to speed anything up or change our roadmap.

**Comment by nuno-vieira** [comment]
Hi @jfru @AndrewSB!

The issue has been fixed in the 4.23.0 release! 🚀

Best,
Nuno

**Comment by jfru** [comment]
Great news. Thanks guys!

**Comment by saidReclip** [comment]
hey @nuno-vieira. This feature now works fine, but I am still getting an error "Search failed with error: Cannot use offset pagination with sort values. Use the next parameter to paginate instead." while **it is working correctly**.

**Comment by nuno-vieira** [comment]
Hi @saidReclip, when do you call this function? Can you show a snippet?

**Comment by saidReclip** [comment]
@nuno-vieira when last item in array appears I call ChatMessageSearchController's func loadNextMessages and get this error. We get the error only when there is no next page.

**Comment by saidReclip** [comment]
Hello @nuno-vieira! Did you have a chance to check it out?

**Comment by nuno-vieira** [comment]
> Hello @nuno-vieira! Did you have a chance to check it out? 

No, not yet. Feel free to open a new issue. But since it is a logging issue, it will be low priority.
