### ISSUE TITLE
Channels do not load correctly after calling `Client.shared.disconnect()` and then setting another user

### ISSUE THREAD

**Issue by KevinMiller-TheWing** [GetStream/stream-chat-swift#274]
## What did you do?
When logging out a user, I call `Client.shared.disconnect()` I then am setting another user as usual. 

## What did you expect to happen?
The channels to load

## What happened instead?
No channels loaded

## GetStream Environment
**GetStream Chat version:** 2.2.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.3 (same issue on 12.2) 
**Swift version:** 5
**Xcode version:** 11.3.1
**Device:** iPhone 11

## Additional context

I am using a subclass of `ChannelsViewController` nested within a parent view controller.  This is all in a tab bar. Upon logout the rootviewController is set to nil.  Looking at the logs in the console, it seems that upon logging in the ChannelsViewController is setting filters differently:

The payload from the initial channel query: 
`▫️ payload={
  "presence" : true,
  "filter_conditions" : {
    "members" : {
      "$in" : [
        "yBR8Gh6RKayzAWuij"
      ]
    }
  },
  "state" : true,
  "message_limit" : 25,
  "watch" : true,
  "limit" : 20
}`

The payload from the query AFTER logging out and setting a user. The id in the filters appear to be the channel Ids from the channels that were displayed after the first call. However the `ChannelsViewController` subclass does not display any channels.  Happy to provide more of the logs if necessary. 

`
▫️ payload={
  "filter_conditions" : {
    "cid" : {
      "$in" : [
        "messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC",
        "messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977",
        "messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966",
        "messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE"
      ]
    }
  },
  "watch" : true,
  "message_limit" : 1,
  "limit" : 1
}`

I believe this may be related to [this issue](https://github.com/GetStream/stream-chat-swift/issues/267)

**Comment by buh** [comment]
Hi @KevinMiller-TheWing  
Thanks!  I'll take a look.
Do you mean #267?

**Comment by KevinMiller-TheWing** [comment]
> Hi @KevinMiller-TheWing
> Thanks! I'll take a look.
> Do you mean #267?

Yes, I do! Thanks :)

**Comment by buh** [comment]
Can you send me logs?

**Comment by KevinMiller-TheWing** [comment]
Sorry, I set my `MainTabBarController` to nil, however it looks like my subclass of `ChannelsViewController` does not get deallocated. 

Here's the log from when I call `Client.shared.disconnect()` and then reconnect: 

```
🐴 [13 May 17:29:58.507] Disconnecting deliberately...
🦄 [13 May 17:29:58.507] Clearing state after disconnect...
🦄 [13 May 17:29:58.507] Cancelling background work...
🦄 [13 May 17:29:58.507] Disconnecting: Resetting connection
🦄 [13 May 17:29:58.507] Parsing WebSocket disconnect... (error: <nil>)
🦄 [13 May 17:29:58.507] Clearing state after disconnect...
🦄 [13 May 17:29:58.507] Cancelling background work...
🦄 [13 May 17:29:58.507] 💔 Disconnected
🕸 State: unknown (-R -------)
🕸 Notifying stopped 🚶‍♂️
🐴 [13 May 17:30:09.927] Disconnecting deliberately...
🦄 [13 May 17:30:09.928] Clearing state after disconnect...
🦄 [13 May 17:30:09.928] Cancelling background work...
🦄 [13 May 17:30:09.928] Skip disconnecting: WebSocket was not connected
🦄 [13 May 17:30:09.928] Clearing state after disconnect...
🦄 [13 May 17:30:09.929] Cancelling background work...
🦄 [13 May 17:30:09.929] Skip disconnecting: WebSocket was not connected
🐴 [13 May 17:30:09.929] 🀄️ Request for a new token from a token provider.
🕸 Notifying stopped 🚶‍♂️
👤 {user_id}: {user_id}
🀄️ Token: {token}
🐴 [13 May 17:30:10.295] Request headers:
◾️ X-Stream-Client = stream-chat-swift-client-2.2.0
◾️ X-Stream-BundleId = {bundle_id}
◾️ X-Stream-App-Environment = development
◾️ Authorization = {token}
◾️ Stream-Auth-Type = jwt
◾️ X-Stream-Device = x86_64
◾️ X-Stream-OS = iOS13.3

🕸 Notifying started 🏃‍♂️
🕸 State: available (-R -------)
🦄 [13 May 17:30:10.348] Cancelling background work...
🦄 [13 May 17:30:10.348] Connecting...
🦄 [13 May 17:30:10.348] ➡️ GET wss://chat-proxy-us-east.stream-io-api.com/connect?api_key={api_key}&authorization={token}&stream-auth-type=jwt&json=%7B%22user_id%22:%22{user_id}%22,%22user_token%22:%22{token}%22,%22server_determines_connection_id%22:true,%22user_details%22:%7B%22id%22:%22{user_id}%22%7D%7D
🦄 [13 May 17:30:10.348] URL query items:
▫️ authorization={token}
▫️ stream-auth-type=jwt
▫️ json={
  "user_id" : "{user_id}",
  "user_token" : "{token}",
  "server_determines_connection_id" : true,
  "user_details" : {
    "id" : "{user_id}"
  }
}
🦄 [13 May 17:30:10.744] ❤️ Connected. Waiting for the current user data and connectionId...
🦄 [13 May 17:30:10.753] healthCheck 👤 {user_id}
🦄 [13 May 17:30:10.753] 📦  {
  "created_at" : "2020-05-13T21:30:10.740576696Z",
  "me" : {
    "unread_count" : 0,
    "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
    "updated_at" : "2020-05-13T20:53:07.700864Z",
    "total_unread_count" : 0,
    "mutes" : [

    ],
    "unread_channels" : 0,
    "devices" : [

    ],
    "name" : "Kevin Test",
    "last_active" : "2020-05-13T21:30:10.736352168Z",
    "banned" : false,
    "id" : "{user_id}",
    "roles" : [

    ],
    "employee" : true,
    "role" : "user",
    "created_at" : "2020-04-29T17:37:53.415366Z",
    "channel_mutes" : [

    ],
    "headline" : "Software Engineer at The Wing",
    "profileComplete" : 14,
    "online" : true,
    "invisible" : false
  },
  "type" : "health.check",
  "connection_id" : "a7ccfd84-5a5b-4211-a7ec-fa48b5af401a",
  "cid" : "*"
}
🦄 [13 May 17:30:10.753] 🥰 Connected
🐴 [13 May 17:30:10.755] Request: channels(StreamChatClient.ChannelsQuery(filter: cid IN ([messaging:454F4E84-FF4E-4415-82B4-2EF07E92D...
🐴 [13 May 17:30:10.755] ➡️ GET https://chat-proxy-us-east.stream-io-api.com/channels?api_key={api_key}&connection_id=a7ccfd84-5a5b-4211-a7ec-fa48b5af401a&payload=%7B%22limit%22:1,%22watch%22:true,%22message_limit%22:1,%22filter_conditions%22:%7B%22cid%22:%7B%22$in%22:%5B%22messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC%22,%22messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977%22,%22messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966%22,%22messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE%22%5D%7D%7D%7D
🐴 [13 May 17:30:10.755] URL query items:
▫️ connection_id=a7ccfd84-5a5b-4211-a7ec-fa48b5af401a
▫️ payload={
  "filter_conditions" : {
    "cid" : {
      "$in" : [
        "messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC",
        "messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977",
        "messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966",
        "messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE"
      ]
    }
  },
  "watch" : true,
  "message_limit" : 1,
  "limit" : 1
}

🐴 [13 May 17:30:10.887] ⬅️ Response 200 (4319 bytes): https://chat-proxy-us-east.stream-io-api.com/channels?api_key={api_key}&connection_id=a7ccfd84-5a5b-4211-a7ec-fa48b5af401a&payload=%7B%22limit%22:1,%22watch%22:true,%22message_limit%22:1,%22filter_conditions%22:%7B%22cid%22:%7B%22$in%22:%5B%22messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC%22,%22messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977%22,%22messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966%22,%22messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE%22%5D%7D%7D%7D
🐴 [13 May 17:30:10.887] 📦 {
  "channels" : [
    {
      "messages" : [
        {
          "id" : "10229117-9864-40be-8022-a215c89bd663",
          "reaction_counts" : {

          },
          "silent" : false,
          "created_at" : "2020-05-13T21:13:28.929198Z",
          "reaction_scores" : {

          },
          "type" : "regular",
          "latest_reactions" : [

          ],
          "text" : "Test",
          "attachments" : [

          ],
          "own_reactions" : [

          ],
          "updated_at" : "2020-05-13T21:13:28.929198Z",
          "reply_count" : 0,
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "latest_hidden_channels" : [

            ],
            "last_active" : "2020-05-13T20:53:07.695932Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "headline" : "Software Engineer at The Wing",
            "profileComplete" : 14,
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-13T20:53:07.700864Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          },
          "mentioned_users" : [

          ],
          "html" : "<p>Test<\/p>\n"
        }
      ],
      "watcher_count" : 1,
      "channel" : {
        "last_message_at" : "2020-05-13T21:13:28.929198Z",
        "created_by" : {
          "id" : "{user_id}",
          "banned" : false,
          "latest_hidden_channels" : [

          ],
          "last_active" : "2020-05-13T20:53:07.695932Z",
          "created_at" : "2020-04-29T17:37:53.415366Z",
          "headline" : "Software Engineer at The Wing",
          "profileComplete" : 14,
          "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
          "employee" : true,
          "updated_at" : "2020-05-13T20:53:07.700864Z",
          "role" : "user",
          "online" : true,
          "name" : "Kevin Test"
        },
        "frozen" : false,
        "id" : "454F4E84-FF4E-4415-82B4-2EF07E92D1FC",
        "created_at" : "2020-05-08T18:05:44.346042Z",
        "member_count" : 2,
        "config" : {
          "automod_behavior" : "flag",
          "reactions" : true,
          "typing_events" : true,
          "mutes" : true,
          "max_message_length" : 5000,
          "created_at" : "2020-05-11T14:35:16.956001512Z",
          "automod" : "disabled",
          "read_events" : true,
          "commands" : [
            {
              "set" : "fun_set",
              "args" : "[text]",
              "name" : "giphy",
              "description" : "Post a random gif to the channel"
            }
          ],
          "connect_events" : true,
          "replies" : true,
          "updated_at" : "2020-05-11T14:35:16.956001686Z",
          "url_enrichment" : true,
          "search" : true,
          "message_retention" : "infinite",
          "uploads" : true,
          "name" : "messaging"
        },
        "type" : "messaging",
        "updated_at" : "2020-05-08T18:05:44.346042Z",
        "cid" : "messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC"
      },
      "read" : [
        {
          "unread_messages" : 0,
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "latest_hidden_channels" : [

            ],
            "last_active" : "2020-05-13T20:53:07.695932Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "headline" : "Software Engineer at The Wing",
            "profileComplete" : 14,
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-13T20:53:07.700864Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          },
          "last_read" : "2020-05-08T18:05:44.410941184Z"
        },
        {
          "unread_messages" : 56,
          "user" : {
            "banned" : false,
            "online" : false,
            "id" : "{user2_id}",
            "role" : "user",
            "created_at" : "2020-04-29T20:03:31.121547Z",
            "deleted_at" : "2020-04-29T20:13:41.181405Z",
            "updated_at" : "2020-04-29T20:03:31.121859Z"
          },
          "last_read" : "2020-05-08T18:05:44.406160128Z"
        }
      ],
      "members" : [
        {
          "created_at" : "2020-05-08T18:05:44.39797Z",
          "updated_at" : "2020-05-08T18:05:44.39797Z",
          "role" : "member",
          "user" : {
            "banned" : false,
            "online" : false,
            "id" : "{user2_id}",
            "role" : "user",
            "created_at" : "2020-04-29T20:03:31.121547Z",
            "deleted_at" : "2020-04-29T20:13:41.181405Z",
            "updated_at" : "2020-04-29T20:03:31.121859Z"
          }
        },
        {
          "created_at" : "2020-05-08T18:05:44.39797Z",
          "updated_at" : "2020-05-08T18:05:44.39797Z",
          "role" : "owner",
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "latest_hidden_channels" : [

            ],
            "last_active" : "2020-05-13T20:53:07.695932Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "profileComplete" : 14,
            "headline" : "Software Engineer at The Wing",
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-13T20:53:07.700864Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          }
        }
      ],
      "membership" : {
        "created_at" : "2020-05-08T18:05:44.39797Z",
        "updated_at" : "2020-05-08T18:05:44.39797Z",
        "role" : "channel_member",
        "user" : {
          "id" : "{user_id}",
          "banned" : false,
          "latest_hidden_channels" : [

          ],
          "last_active" : "2020-05-13T20:53:07.695932Z",
          "created_at" : "2020-04-29T17:37:53.415366Z",
          "profileComplete" : 14,
          "headline" : "Software Engineer at The Wing",
          "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
          "employee" : true,
          "updated_at" : "2020-05-13T20:53:07.700864Z",
          "role" : "user",
          "online" : true,
          "name" : "Kevin Test"
        }
      }
    }
  ],
  "duration" : "14.04ms"
}
🦄 [13 May 17:30:36.754] 🏓➡️
🦄 [13 May 17:30:36.780] ⬅️🏓
🦄 [13 May 17:31:01.745] 🏓➡️
🦄 [13 May 17:31:01.773] ⬅️🏓
🦄 [13 May 17:31:25.754] 🏓➡️
🦄 [13 May 17:31:25.779] ⬅️🏓
```

**Comment by buh** [comment]
Thanks!
Did you deliberately make sure that your subclass wasn't deallocated?

**Comment by KevinMiller-TheWing** [comment]
Sure thing! No, I didn't... I checked all the references in it and I shouldn't have any retain cycles.

**Comment by buh** [comment]
Hi @KevinMiller-TheWing
We released 2.2.1 Can you check it for this issue?

**Comment by KevinMiller-TheWing** [comment]
Hi, @buh unfortunately it didn't fix it. Here's the log after logging out.  I've noticied that I only have this issue if the `ChatViewController` subclass has been initialized. If I log out and log back in without having initialized the `ChatViewController` subclass, it retrieves my channels no problem

```
[20 May 11:01:34.486] [DEBUG] Disconnecting deliberately...
[20 May 11:01:34.486] [DEBUG] Clearing state after disconnect...
[20 May 11:01:34.486] [DEBUG] Cancelling background work...
[20 May 11:01:34.486] [DEBUG] Disconnecting: Resetting connection
[20 May 11:01:34.487] [DEBUG] Clearing state after disconnect...
[20 May 11:01:34.487] [DEBUG] Cancelling background work...
[20 May 11:01:34.487] [DEBUG] Skip disconnecting: WebSocket was not connected
[20 May 11:01:34.487] [DEBUG] 🀄️ Request for a new token from a token provider.
[20 May 11:01:34.842] [DEBUG] Notifying stopped 🚶‍♂️
2020-05-20 11:01:34.841905-0400 Wicked[52643:2438192] [APPBOY] Got request to 
[20 May 11:01:34.851] [INFO] {user_id}: {user_id}
[20 May 11:01:34.851] [INFO] Token: {token}
[20 May 11:01:34.853] [INFO] Request headers:
	◾️ X-Stream-Device = x86_64
	◾️ Stream-Auth-Type = jwt
	◾️ X-Stream-Client = stream-chat-swift-client-2.2.1
	◾️ X-Stream-OS = iOS13.4.1
	◾️ X-Stream-App-Environment = development
	◾️ X-Stream-BundleId = com.the-wing.thewing.debug
	◾️ Authorization = {token}

[20 May 11:01:34.884] [DEBUG] Notifying started 🏃‍♂️
[20 May 11:01:34.884] [DEBUG] State: available (-R -------)
[20 May 11:01:34.884] [DEBUG] Cancelling background work...
[20 May 11:01:34.884] [DEBUG] Connecting...
[20 May 11:01:34.884] [DEBUG] ➡️ GET wss://chat-proxy-us-east.stream-io-api.com/connect?api_key={api_key}&authorization={token}&stream-auth-type=jwt&json=%7B%22user_id%22:%22{user_id}%22,%22user_token%22:%22{token}%22,%22server_determines_connection_id%22:true,%22user_details%22:%7B%22id%22:%22{user_id}%22%7D%7D
[20 May 11:01:34.884] [DEBUG] URL query items:
▫️ authorization={token}
▫️ stream-auth-type=jwt
▫️ json={
  "user_id" : "{user_id}",
  "user_token" : "{token}",
  "server_determines_connection_id" : true,
  "user_details" : {
    "id" : "{user_id}"
  }
}

[20 May 11:01:35.275] [DEBUG] ❤️ Connected. Waiting for the current user data and connectionId...
[20 May 11:01:35.287] [DEBUG] healthCheck 👤 {user_id}
[20 May 11:01:35.287] [INFO] 📦  {
  "created_at" : "2020-05-20T15:01:35.273055717Z",
  "me" : {
    "unread_count" : 0,
    "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
    "updated_at" : "2020-05-20T14:43:58.328015Z",
    "total_unread_count" : 0,
    "mutes" : [

    ],
    "unread_channels" : 0,
    "devices" : [
      {
        "id" : "42e7861d9a78477c9c1ee4fd1a830cbe7db270d21ee4599b241622bb2285f344",
        "push_provider" : "apn",
        "user_id" : "{user_id}",
        "created_at" : "2020-05-18T21:54:04.212757Z"
      }
    ],
    "name" : "Kevin Test",
    "last_active" : "2020-05-20T15:01:35.2660539Z",
    "banned" : false,
    "id" : "{user_id}",
    "roles" : [

    ],
    "employee" : true,
    "role" : "user",
    "created_at" : "2020-04-29T17:37:53.415366Z",
    "channel_mutes" : [

    ],
    "profileComplete" : 14,
    "headline" : "Software Engineer at The Wing",
    "online" : true,
    "invisible" : false
  },
  "type" : "health.check",
  "connection_id" : "656e8149-6f34-4dd4-a1a8-1c14a2bee607",
  "cid" : "*"
}
[20 May 11:01:35.287] [DEBUG] 🥰 Connected
[20 May 11:01:35.288] [DEBUG] Request: channels(StreamChatClient.ChannelsQuery(filter: cid IN ([messaging:367FF172-1FE9-47B0-B720-B7FFF37DA...
[20 May 11:01:35.289] [DEBUG] ➡️ GET https://chat-proxy-us-east.stream-io-api.com/channels?api_key={api_key}&connection_id=656e8149-6f34-4dd4-a1a8-1c14a2bee607&payload=%7B%22limit%22:1,%22watch%22:true,%22message_limit%22:1,%22filter_conditions%22:%7B%22cid%22:%7B%22$in%22:%5B%22messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977%22,%22messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE%22,%22messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C%22,%22messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966%22,%22messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC%22%5D%7D%7D%7D
[20 May 11:01:35.289] [DEBUG] URL query items:
▫️ connection_id=656e8149-6f34-4dd4-a1a8-1c14a2bee607
▫️ payload={
  "filter_conditions" : {
    "cid" : {
      "$in" : [
        "messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977",
        "messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE",
        "messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C",
        "messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966",
        "messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC"
      ]
    }
  },
  "watch" : true,
  "message_limit" : 1,
  "limit" : 1
}

[20 May 11:01:35.314] [INFO] 🏓➡️
[20 May 11:01:35.339] [INFO] ⬅️🏓
[20 May 11:01:35.425] [DEBUG] ⬅️ Response 200 (4567 bytes): https://chat-proxy-us-east.stream-io-api.com/channels?api_key={api_key}&connection_id=656e8149-6f34-4dd4-a1a8-1c14a2bee607&payload=%7B%22limit%22:1,%22watch%22:true,%22message_limit%22:1,%22filter_conditions%22:%7B%22cid%22:%7B%22$in%22:%5B%22messaging:367FF172-1FE9-47B0-B720-B7FFF37DA977%22,%22messaging:93A8CF5D-4E77-432A-A71F-8B756AED85CE%22,%22messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C%22,%22messaging:443ABC25-2E2E-4529-B33A-D85CF1B10966%22,%22messaging:454F4E84-FF4E-4415-82B4-2EF07E92D1FC%22%5D%7D%7D%7D
[20 May 11:01:35.425] [INFO] 📦 {
  "channels" : [
    {
      "messages" : [
        {
          "id" : "8ee103d9-5964-4221-8414-f3b6cb16681a",
          "reaction_counts" : {

          },
          "silent" : false,
          "created_at" : "2020-05-20T14:44:09.309897Z",
          "reaction_scores" : {

          },
          "type" : "regular",
          "latest_reactions" : [

          ],
          "text" : "Chat\n",
          "attachments" : [

          ],
          "own_reactions" : [

          ],
          "updated_at" : "2020-05-20T14:44:09.309897Z",
          "reply_count" : 0,
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "last_active" : "2020-05-20T14:43:58.3269Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "headline" : "Software Engineer at The Wing",
            "profileComplete" : 14,
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-20T14:43:58.328015Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          },
          "mentioned_users" : [

          ],
          "html" : "<p>Chat<br\/><\/p>\n"
        }
      ],
      "watcher_count" : 1,
      "channel" : {
        "last_message_at" : "2020-05-20T14:44:09.309897Z",
        "created_by" : {
          "id" : "{user_id}",
          "banned" : false,
          "last_active" : "2020-05-20T14:43:58.3269Z",
          "created_at" : "2020-04-29T17:37:53.415366Z",
          "profileComplete" : 14,
          "headline" : "Software Engineer at The Wing",
          "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
          "employee" : true,
          "updated_at" : "2020-05-20T14:43:58.328015Z",
          "role" : "user",
          "online" : true,
          "name" : "Kevin Test"
        },
        "frozen" : false,
        "id" : "827E6269-AFB0-4BD5-B519-AD519F72F54C",
        "created_at" : "2020-05-19T15:26:42.43588Z",
        "member_count" : 2,
        "config" : {
          "automod_behavior" : "flag",
          "reactions" : false,
          "typing_events" : true,
          "mutes" : false,
          "max_message_length" : 5000,
          "created_at" : "2020-05-19T13:53:39.924519Z",
          "automod" : "disabled",
          "read_events" : true,
          "commands" : [
            {
              "set" : "fun_set",
              "args" : "[text]",
              "name" : "giphy",
              "description" : "Post a random gif to the channel"
            }
          ],
          "connect_events" : true,
          "replies" : false,
          "updated_at" : "2020-05-19T13:54:25.859082Z",
          "url_enrichment" : true,
          "search" : true,
          "message_retention" : "infinite",
          "uploads" : true,
          "name" : "messaging"
        },
        "type" : "messaging",
        "updated_at" : "2020-05-19T15:26:42.43588Z",
        "cid" : "messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C"
      },
      "read" : [
        {
          "unread_messages" : 4,
          "user" : {
            "id" : "ip2jAnonX82haeXqx",
            "banned" : false,
            "last_active" : "2020-05-20T14:43:32.861717Z",
            "created_at" : "2020-05-14T18:34:36.700772Z",
            "headline" : "Songwriter at",
            "profileComplete" : 15,
            "image" : "https:\/\/the-wing-backend-api.s3.amazonaws.com\/app\/ip2janonx82ha-b5e-645a22368b58exqx",
            "employee" : false,
            "updated_at" : "2020-05-20T14:43:32.865031Z",
            "role" : "user",
            "online" : false,
            "name" : "Lisa Marie Fifty-One"
          },
          "last_read" : "2020-05-19T19:04:26.119939584Z"
        },
        {
          "unread_messages" : 0,
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "last_active" : "2020-05-20T14:43:58.3269Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "profileComplete" : 14,
            "headline" : "Software Engineer at The Wing",
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-20T14:43:58.328015Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          },
          "last_read" : "2020-05-19T19:08:57.726952192Z"
        }
      ],
      "members" : [
        {
          "created_at" : "2020-05-19T15:26:42.496077Z",
          "updated_at" : "2020-05-19T15:26:42.496077Z",
          "role" : "member",
          "user" : {
            "id" : "ip2jAnonX82haeXqx",
            "banned" : false,
            "last_active" : "2020-05-20T14:43:32.861717Z",
            "created_at" : "2020-05-14T18:34:36.700772Z",
            "profileComplete" : 15,
            "headline" : "Songwriter at",
            "image" : "https:\/\/the-wing-backend-api.s3.amazonaws.com\/app\/ip2janonx82ha-b5e-645a22368b58exqx",
            "employee" : false,
            "updated_at" : "2020-05-20T14:43:32.865031Z",
            "role" : "user",
            "online" : false,
            "name" : "Lisa Marie Fifty-One"
          }
        },
        {
          "created_at" : "2020-05-19T15:26:42.496078Z",
          "updated_at" : "2020-05-19T15:26:42.496078Z",
          "role" : "owner",
          "user" : {
            "id" : "{user_id}",
            "banned" : false,
            "last_active" : "2020-05-20T14:43:58.3269Z",
            "created_at" : "2020-04-29T17:37:53.415366Z",
            "profileComplete" : 14,
            "headline" : "Software Engineer at The Wing",
            "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
            "employee" : true,
            "updated_at" : "2020-05-20T14:43:58.328015Z",
            "role" : "user",
            "online" : true,
            "name" : "Kevin Test"
          }
        }
      ],
      "membership" : {
        "created_at" : "2020-05-19T15:26:42.496078Z",
        "updated_at" : "2020-05-19T15:26:42.496078Z",
        "role" : "channel_member",
        "user" : {
          "id" : "{user_id}",
          "banned" : false,
          "last_active" : "2020-05-20T14:43:58.3269Z",
          "created_at" : "2020-04-29T17:37:53.415366Z",
          "profileComplete" : 14,
          "headline" : "Software Engineer at The Wing",
          "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
          "employee" : true,
          "updated_at" : "2020-05-20T14:43:58.328015Z",
          "role" : "user",
          "online" : true,
          "name" : "Kevin Test"
        }
      }
    }
  ],
  "duration" : "7.84ms"
}
[20 May 11:01:35.487] [DEBUG] userStartWatching 🆔 messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C 👤 {user_id}
[20 May 11:01:35.487] [INFO] 📦  {
  "user" : {
    "id" : "{user_id}",
    "banned" : false,
    "last_active" : "2020-05-20T14:43:58.3269Z",
    "created_at" : "2020-04-29T17:37:53.415366Z",
    "profileComplete" : 14,
    "headline" : "Software Engineer at The Wing",
    "image" : "https:\/\/the-wing-backend-api.s3.us-east-2.amazonaws.com\/app\/ybr8gh6rkayza-92d-9ef8c029e9efwuij",
    "employee" : true,
    "updated_at" : "2020-05-20T14:43:58.328015Z",
    "role" : "user",
    "online" : true,
    "name" : "Kevin Test"
  },
  "watcher_count" : 1,
  "created_at" : "2020-05-20T15:01:35.410200042Z",
  "type" : "user.watching.start",
  "cid" : "messaging:827E6269-AFB0-4BD5-B519-AD519F72F54C"
}
[20 May 11:02:00.699] [INFO] 🏓➡️
```

**Comment by vadubov** [comment]
> I've noticied that I only have this issue if the `ChannelsViewController` subclass has been initialized. If I log out and log back in without having initialized the `ChannelsViewController` subclass, it retrieves my channels no problem

I checked and have the same behaviour: channels doesn't load after relogin only if `ChannelsViewController` was initialized in previous session.

**Comment by buh** [comment]
I think I found the issue. The fix in branch `fix-rx-reconnection`. Can you check it?
```ruby
  pod 'StreamChat', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
  pod 'StreamChatCore', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
  pod 'StreamChatClient', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
```

**Comment by KevinMiller-TheWing** [comment]
Works great! Thank you!

**Comment by KevinMiller-TheWing** [comment]
Glad this fix works... any ideas when 2.2.3 will be released with this fix?

**Comment by buh** [comment]
Hi @KevinMiller-TheWing!
It will on this week. Probably tomorrow :)

**Comment by KevinMiller-TheWing** [comment]
Perfect, thanks :)

**Comment by buh** [comment]
Hi @KevinMiller-TheWing 
Please can you check the branch again with the latest changes for the reconnection issue? We are going to release it.
```ruby
pod 'StreamChat', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
pod 'StreamChatCore', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
pod 'StreamChatClient', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix-rx-reconnection'
```

**Comment by KevinMiller-TheWing** [comment]
Yep, looks good still! 👍

**Comment by buh** [comment]
Thanks!

**Comment by b-onc** [comment]
Closed via #284
